compute_environment: LOCAL_MACHINE
distributed_type: NO # NO MULTI_GPU
# Mixed precision options: "no", "fp16", "bf16"
mixed_precision: "bf16"
num_processes: 1
gpu_ids: "3"
use_cpu: false
num_machines: 1
machine_rank: 0