# 需要修改的
batch_size: 10
load_sam_pretrained_checkpoint: null
load_siglip_pretrained_checkpoint: null
sam_model_name: "sam_base"
siglip_model_name: "ViT-B-16-SigLIP-384"
dataset_path: "/data2/wang_tong/proj_cirseg/28_dataset_cirseg_2_9_all/cirseg_2_9_dataset"
train_csv: "/data2/wang_tong/proj_cirseg/31_dataset_cirseg_4_0/cirseg_4_1_csv_data/Train.csv"
val_csv_A: "/data2/wang_tong/proj_cirseg/31_dataset_cirseg_4_0/cirseg_4_1_csv_data/Test_1.csv"
val_csv_B: "/data2/wang_tong/proj_cirseg/31_dataset_cirseg_4_0/cirseg_4_1_csv_data/Test_2.csv"
vaild_model_save_path: "/data2/wang_tong/proj_cirseg/my_models/models_ckpt/DGX_32/experiment_eval_10"
mask_pooling: "MaskAdapterPooling" # MaskedPooling or MaskAdapterPooling
multimask_output: false
load_checkpoint_path: "/data2/wang_tong/proj_cirseg/my_models/models_ckpt/DGX_32/checkpoint_epoch_10.pth"

